### ISSUE TITLE
Desktop app is not uploading file

### ISSUE THREAD

**Issue by benbouillet** [internxt/drive-desktop#1]
Hi,
Desktop app is not uploading file.
Mac OSX : 10.14.6
Running behind a company network.

Behavior : 2 files (one .png 39kb & one .mp4 4.2mb) copied into the XCloud folder designated at first launch. I can't see the file in both web app & mobile app.

Note : I uploaded a file via the web app, and I'm able to see it on my mobile app.

**Comment by benbouillet** [comment]
FYI : I tried the same process, but from a hotspot connection (through my mobile) : same result

**Comment by fvsegarra** [comment]
Please try now
