### ISSUE TITLE
Minimizing after tryping to open it

### ISSUE THREAD

**Issue by davidk55** [internxt/drive-desktop#103]
### The Problem
- Every time after I am trying to open the Internxt Drive it minimize instantly by itself

https://user-images.githubusercontent.com/67225198/166446003-804456b4-66a8-4ca2-aabf-696cfb7deb93.mp4

### My Environment
- **OS**: Arch Linux
- **Window Manager**: AwesomeWM
- **Version**: Internxt-Drive 1.8.0 AppImage (as seen in the video)
- **To Note**: never had similar issues with other electron based applications as AppImages

**Comment by AlexMenor** [comment]
Hi @davidk55, our desktop app behaves like a widget, its minimised when losing focus. It seems like when your cursor moves on top of another window this window gains focus without you having to click.

**Comment by davidk55** [comment]
Hey @AlexMenor, you are right, that is exactly what caused that. Sadly it will be hard for me to use, but thanks for the fast reply
