### ISSUE TITLE
Desktop app issues on rename, delete, update

### ISSUE THREAD

**Issue by iltrex** [internxt/drive-desktop#104]
Version 1.8.0.
I rename 11 files in the local folder one 1st pc. Even after 2 hours, 2nd pc do not sync.
The cloud received the rename for just 1 file.
I click the "play" button on the 2nd pc. It downloads the renamed file, but also upload the OLD files with the original name. So I end up with both old and new file.

I renamed again a file, but the rename is never synced to the cloud.

the pc desktop app is pretty broken and currently unusable.

**Comment by Desibabe** [comment]
I can't delete a file, after clicking DELETE button nothing happens. No error message I must have done 10 times several days. Do you guys have this issue?
