### ISSUE TITLE
KDE DE Integration

### ISSUE THREAD

**Issue by noticons** [internxt/drive-desktop#109]
I'm using KDE, but the desktop syncing app (version 1.90) doesn't seem to integrate well with this DE. When I click on the icon in the system tray, the popup will appear in the upper left portion of the desktop with no window border, ability to be dragged on the screen, or manner to dismiss the popup. I can click the settings-->preferences option, and it appears as a regular window with full functionality.

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
X11

![image](https://user-images.githubusercontent.com/79101622/172626411-06d3b152-0a78-49c9-8db2-bf93baea97e4.png)

**Comment by lukaskretzschmer** [comment]
On PopOS also an issue with the tray icon, when you click it the window dissapears instantly.

**Comment by LanceHaverkamp** [comment]
I'm seeing a somewhat different, but probably related issue:
Once the syncing app opens in the upper left, it seems to work, but once it minimizes to the tray, it can not ever open again. I can run the program from the menu again, but then I get multiple instances of the same account running concurrently.

System Tray, showing three X icons, non of which are interactive:
![image](https://user-images.githubusercontent.com/15806629/212602206-925aa940-1673-4071-b8d6-3901d26c0ae0.png)

System monitor, showing three apps running:
![Screenshot_20230115_220318](https://user-images.githubusercontent.com/15806629/212602434-c6ac1225-b75b-4f9e-ad30-18f1fd366b97.png)
