### ISSUE TITLE
Support symbolic link on Windows

### ISSUE THREAD

**Issue by vitalyobukhov** [internxt/drive-desktop#115]
The current version of desktop Internxt Drive for Windows doesn't support symbolic links in a valid way: it reports them as zero-size files and tries to sync their content again and again:
> File is empty 
> We don't support files with a size of 0 bytes because of our processes of sharding and encryption

I can't use the app without this functionality due to the way how my data organized through partitions and NAS.

**Comment by jrhellriegeljr** [comment]
Same.

**Comment by vitalyobukhov** [comment]
Side-note: there's a selective backup functionality which is said to be one-way sync, not selective mirroring. Unfortunately, even a browsing of these files isn't supported by mobile clients at the current time. A desktop web version of the service doesn't work on mobile either. So there's not enought functionality to cover the selective sync case which actually is frustrating.
