### ISSUE TITLE
Internxt not launching from tray on Linux

### ISSUE THREAD

**Issue by lukaskretzschmer** [internxt/drive-desktop#118]
I reported this several month ago but the issue still persists, the popout window doesn't stay open or it doesn't show at all when clicking the tray icons, so it's basically useless. This is on pop_os
 I don't know if other users have this issue as well.
This video shows the issue
[Youtube Video](https://www.youtube.com/watch?v=g_lpKgwPYnQ&feature=youtu.be)

**Comment by edav-mx** [comment]
Have a similar same problem in Elementary OS. Proper support for linux is pretty low compared to other operative systems...

**Comment by RasheedAZ** [comment]
> 

Same problem. Pop!_OS 22.04 Gnome 42.3.1

**Comment by rustbuckett** [comment]
Same issue using Pop!_OS 22.04 LTS and Gnome 42.5. Windowing system is X11, not Wayland like I thought it would be. When I click the tray icon, the only option is "Internxt Drive 1.9.6", no option for preferences, quit, or anything. When I click this single option, one of my tiled windows resizes briefly, then nothing else. If I close the app (running from appimage currently) and restart it, I get a window where I can open Preferences. If I close the window, I have to kill the app and start it again to get a window back.

**Comment by alexanderantonov** [comment]
The same problem in Ubuntu 22.04.

**Comment by ismo-conguairta** [comment]
Similar issue on Debian and i3wm with version 1.9.8. After clicking the single option on tray icon the floating window quickly disappears. I have to move the pointer quickly and sometimes I'm able to make window remain persistent on the screen.

**Comment by RasheedAZ** [comment]
Note sure if this was fixed. Anyone had this working with latest version?

**Comment by rustbuckett** [comment]
When I was having trouble with it before, I was using Sway on Wayland. It seems to work fine now with KDE Plasma on X11. I don't know if it would work with my old config, so I can't say whether it's an issue with Wayland and/or Sway.
