### ISSUE TITLE
Tray for Linux not implemented

### ISSUE THREAD

**Issue by lukaskretzschmer** [internxt/drive-desktop#120]
I was checking [src/main/tray.ts](https://github.com/internxt/drive-desktop/blob/8ab0c4b75e6a1d6ae5f0567579a934f562eab498/src/main/tray.ts) and I noticed that no tray options are being shown for Linux, also there's a popout that shows null and there is currently an issue which I explained on [https://github.com/internxt/drive-desktop/issues/118](https://github.com/internxt/drive-desktop/issues/118) so maybe this is causing it.

**Comment by edav-mx** [comment]
Hi, just commenting that the implementation for the tray doesn't seem to be complete as it doesn't work for me also.

**Comment by sg-gs** [comment]
Duplicated of #118. We are starting to check these issues now @lukaskretzschmer @edav-mx
