### ISSUE TITLE
Files are lost

### ISSUE THREAD

**Issue by kishanhathiwala** [internxt/drive-desktop#134]
Hello,

I was trying to push multiple folders (approx 100GB in total) in windows pc. It happened that I had to press the STOP/START button multiple times. Every time when I click START button, I could see the files are getting uploaded. 

When about 25GB of files were uploaded, I checked my drive on website, I couldn't find lots of files but at the same time I could see the storage consumption. 

I went to Recent option in web, I could see the files were uploaded but the path was different as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/29030616/194463541-be4e575c-1275-40fa-8bd5-16c5136fca33.png)

And this my screenshot in main drive
![image](https://user-images.githubusercontent.com/29030616/194463869-145669cd-3701-40a0-a334-37736c5c274a.png)

Not sure how can I find my files. Can someone please help?

**Comment by JoanVicens** [comment]
Hi,please refer to [hello@internxt.com](mailto:hello@internxt.com) to report bugs with your accout. Attach the app logs if posible, you can found them going to the app > click on the gear > preferences > Open logs
