### ISSUE TITLE
Slow Upload

### ISSUE THREAD

**Issue by MalteKiefer** [internxt/drive-desktop#14]
I tested a PDF file. 
macOS Client 1.1.9

5 MB file size.
Needed 30 seconds to upload.
iCloud need 5. I know there is encryption.
But that could not be all, or?

**Comment by fvsegarra** [comment]
Client-side encryption + file fragmentation and distribution are the cause. Though slower, it does guarantee significantly higher levels of privacy and security. We're working on improving speed though. Stay tuned for updates!
