### ISSUE TITLE
1.9.5 release is deleting files in server

### ISSUE THREAD

**Issue by adrianinsaval** [internxt/drive-desktop#165]
I updated my client to 1.9.5 on windows and it started deleting files from the server for no reason, this is a critical bug and it's not the first time this happens, you have very serious quality control problems... I can't trust this company like this.

Then after restarting the app it started redownloading files that are already downloaded...

**Comment by JoanVicens** [comment]
Please contact me via jvalles@internxt.com and attach the application logs
