### ISSUE TITLE
symbolic link and send report are not working

### ISSUE THREAD

**Issue by omarb-neodream** [internxt/drive-desktop#173]
Created a symbolic link in Internxt folder : 
`➜  Internxt# ln -s /Users/[homeFolder]/Pictures Pictures  `

<img width="325" alt="Screen Shot 2022-12-16 at 13 08 34" src="https://user-images.githubusercontent.com/6873287/208075187-e98b6e7d-aeae-4166-89f5-163085521003.png">
<img width="495" alt="Screen Shot 2022-12-16 at 13 08 41" src="https://user-images.githubusercontent.com/6873287/208075199-a5c63c6d-84a0-44b2-a6fa-0302ac7dbbc7.png">
<img width="471" alt="Screen Shot 2022-12-16 at 13 08 48" src="https://user-images.githubusercontent.com/6873287/208075204-f73e9280-5000-40b7-836e-54d90a10ccea.png">

Impossible to report, internet is OK
<img width="477" alt="Screen Shot 2022-12-16 at 13 09 09" src="https://user-images.githubusercontent.com/6873287/208075209-670026c7-5708-430e-b0c3-b05ab6159ac5.png">

**Comment by sg-gs** [comment]
We have had issues with our reporting system these days, we have fixed it today @omarb-neodream. We do not still support symbolic links

**Comment by vitalyobukhov** [comment]
Regarding symlinks: https://github.com/internxt/drive-desktop/issues/115
