### ISSUE TITLE
Synced file didn't update on edit.

### ISSUE THREAD

**Issue by AJMitev** [internxt/drive-desktop#19]
I have the same file A.ods on two machines. If I modify the file on machine A then the modified state is never synched to machine B.

**Comment by Barraguesh** [comment]
Have you tried the web drive? Is it updated there?

**Comment by meticoeus** [comment]
I have occasionally noticed that I need to manually tell drive-desktop to sync in the UI before it picks up a change and syncs with the web.

**Comment by AlexMenor** [comment]
Hi, drive desktop syncs every 10 minutes
