### ISSUE TITLE
MacOS Desktop

### ISSUE THREAD

**Issue by zrml** [internxt/drive-desktop#190]
I am not sure how the following warning comes about, perhpas because half of my time I'm connected via VPN to another country but it is very annoying because it means my files are not being backed up... so yes, it is more than annoying, it is dangerous and what I paid for: a sync service.

"Looks like other of your devices is already syncing, we'll try again later"

What does the above message mean and how can I reset it or make sure Internxt starts syncing again?

Thank you very much

**Comment by 2Ben** [comment]
Same issue here. I'm wondering if after a hard reboot, maybe some lock file didn't get deleted or something?

**Comment by zrml** [comment]
@2Ben not sure. I have tried a hard reboot. The issue is still present.
It would be nice to have some comments from Internxt...
thank you guys
