### ISSUE TITLE
can't delete files on desktop

### ISSUE THREAD

**Issue by adrianinsaval** [internxt/drive-desktop#200]
using the desktop sync client, when deleting a file in the filesystem it is redownloaded over and over again no matter how many times I delete, can only delete files from the webpage

**Comment by adrianinsaval** [comment]
this is ridiculous, now I can't even delete on the web interface...

**Comment by rose111data** [comment]
> this is ridiculous, now I can't even delete on the web interface...

I'm having the same issue...quite literally my first day using this. I'm on Windows 11, and the only thing that semi-worked was opening task manager and end multiple Internxt tasks (why this happens, I have no idea), and only then did it allow me to delete anything. I can't delete anything from the online interface, gives me the "error sending to trash". Super frustrating.

**Comment by olaf-lang** [comment]
Same behaviour here. Deleteing does not work, the folder structure that is defined in desktop client is ignored while syncing. The result is really frustrating.

**Comment by olaf-lang** [comment]
Thanks
