### ISSUE TITLE
[Suggestion] Use Flatpak and Flathub

### ISSUE THREAD

**Issue by Barraguesh** [internxt/drive-desktop#21]
I see you have a .deb and .appimage for the desktop app in Linux. I think going appimage and Flatpak would be better because those two are two different options that work across all the distros. Also, using [Flathub](http://flathub.org) for distribution of the Flatpak would make it easier for Linux users to discover and install, giving Internxt a little marketing boost!

I've been researching Flatpak personally and I offer myself as a volunteer to bundle it as a Flatpak in Flathub, but it may take a long time. For what I've seen, Flathub has lots of apps bundled by volunteers, so this would be nothing weird.

**Comment by RasheedAZ** [comment]
Great idea although these kinds of security critical apps should be bundled by the devs, not unknown third parties.

**Comment by Juasmis** [comment]
Any updates on this?

**Comment by RasheedAZ** [comment]
Hi. Is this closed because the the app has been pushed to Flathub? Thanks.

(I paid for a plan but wasn't able to use Internxt for long because the deb was not great :( even on a popular Ubuntu based distro.)

**Comment by ekasprzak** [comment]
Hello @fvsegarra, was this closed as completed because it will be available soon in flathub?
Or you just don't plan to do it (not expecting anything than some explanation on completed status) ?

**Comment by boustanihani** [comment]
A Flatpak/Flathub would be really great.

**Comment by RasheedAZ** [comment]
> Hello [@fvsegarra](https://github.com/fvsegarra), was this closed as completed because it will be available soon in flathub? Or you just don't plan to do it (not expecting anything more than some explanation on completed status) ?

The repo of the Linux app is now separate here: https://github.com/internxt/drive-desktop-linux I'll open a new issue there.
