### ISSUE TITLE
Windows 10 generating COULD_NOT_ACQUIRE_LOCK and NOT_IN_SYNC Errors for a new account with a clean install

### ISSUE THREAD

**Issue by rektdegen** [internxt/drive-desktop#217]
I created an account today on the 2TB Special Offer and on a clean install on the Windows Drive client I'm getting the errors produced in the log file at the bottom of the post.  The two log files are also attached. at the very end of the post.

Any file or folder I delete has the same issue restored due to the errors COULD_NOT_ACQUIRE_LOCK and NOT_IN_SYNC.

The only change I have made to the defualt config is to select a new sync folder, due to a small SSD as my c:\ not having the capacity to also function as a sync storage device.

I selected a folder on a larger HDD directly which is called the same as my Windows 10 Account name, however I did not use Symbolic links, I selected the E:\ and Folder Directly and then created a sub-folder called 'Internxt' to as the target folder.

You've been spamming for years about how good your service is and I tonight thought I'd give the promo a shot with view to long term usage, but we're not really off to a cracking start right now are we, especially as looking at other Live Issues I'm guessing other people could have raised similar issues months ago without update, communication or resolution.

[2023-04-04 05:41:34.174] [info]  Local change(s) detected:  [
  {
    "path": "E:\\[WINDOWS10-USERNAME-NONSYMBOLIC-FOLDER]\\Internxt\\iPad",
    "type": "delete"
  }
]
[2023-04-04 05:41:37.036] [info]  Could not acquire lock Error: Lock for folderId 65933309 with id b311f489-bdac-4d43-b93d-0bc72bea2c57 could not be acquired/refreshed, status: 500 at Object.acquireOrRefreshLock (C:\Users\[windows10-username]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\src\main\background-processes\locks-service.ts:38:9) at processTicksAndRejections (node:internal/process/task_queues:96:5) at C:\Users\[windows10-username]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-rive\src\main\background-processes\sync.ts:142:5
[2023-04-04 05:41:37.038] [info]  [onSyncExit] (COULD_NOT_ACQUIRE_LOCK)  
[2023-04-04 05:41:38.804] [info]  Local change(s) detected:  [
  {
    "path": "E:\\[windows10-username-nonsymbolic-folder]\\Internxt\\iPad",
    "type": "create"
  }
]
[2023-04-04 05:41:38.804] [info]  Local change(s) detected:  [
  {
    "path": "E:\\[windows10-username-nonsymbolic-folder]\\Internxt\\iPad",
    "type": "create"
  }
]
[2023-04-04 05:41:39.890] [info]  [onSyncExit] (EXIT)  NOT_IN_SYNC
[2023-04-04 05:41:43.156] [info]  [onSyncExit] (EXIT)  NOT_IN_SYNC

[main.log](https://github.com/internxt/drive-desktop/files/11143210/main.log)
[renderer.log](https://github.com/internxt/drive-desktop/files/11143212/renderer.log)

**Comment by rektdegen** [comment]
I've fully uninstalled the app.  Every single file related to the Windows Drive App has been deleted.

Once the app was removed everything started functioning correctly again, on iOS and the Web Drive page.  Folders could be deleted and would not return.

I reinstalled the and loaded it up, and straight away before trying to move folders again, I created a new folder to test with and this could not be permentantly remove from the file structure. 

This is the contents of the main.log:

[2023-04-05 11:05:57.851] [info]  Running 1.9.8
[2023-04-05 11:05:57.970] [info]  [TOKEN] Tokens will be refreshed on  14/04/2023
[2023-04-05 11:05:57.975] [info]  Checking for update
[2023-04-05 11:05:59.248] [error] Remote notifications connect error:  Error: xhr poll error
    at g.onError (C:\Users\[Window10-UserName]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\node_modules\engine.io-client\build\cjs\transport.js:45:37)
    at m.apply (C:\Users\[Window10-UserName]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\node_modules\engine.io-client\build\cjs\transports\polling.js:251:18)
    at m.emitReserved [as emit] (C:\Users\[Window10-UserName]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\node_modules\@socket.io\component-emitter\index.mjs:136:20)
    at m.onError (C:\Users\[Window10-UserName]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\node_modules\engine.io-client\build\cjs\transports\polling.js:352:14)
    at Timeout._onTimeout (C:\Users\[Window10-UserName]\AppData\Local\Programs\internxt-drive\resources\app.asar\dist\main\webpack:\internxt-drive\node_modules\engine.io-client\build\cjs\transports\polling.js:325:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[2023-04-05 11:05:59.835] [info]  Remote notifications disconnected, reason:  transport error
[2023-04-05 11:06:01.467] [info]  Update for version 1.9.8 is not available (latest version: 1.9.8, downgrade is disallowed).
[2023-04-05 11:06:01.588] [info]  Remote notifications connected
[2023-04-05 11:06:02.735] [info]  [onSyncExit] (EXIT)  NOT_IN_SYNC

And from the renderer.log:

[2023-04-05 11:06:00.325] [debug] SYNC STARTING 
[2023-04-05 11:06:00.327] [info]  Smoke testing
[2023-04-05 11:06:01.202] [info]  Checking last run outcome
[2023-04-05 11:06:01.203] [debug] Last saved listing: {
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
    modtime: 1680560357,
    size: '549363',
    isFolder: false,
    id: 349246863,
    ino: 18858823439707532,
    dev: 2655223399
  },
  'desktop.ini': {
    modtime: 1680559416,
    size: '46',
    isFolder: false,
    id: 349246287,
    ino: 434034414087847200,
    dev: 2655223399
  },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
    modtime: 1680560599,
    size: '29412',
    isFolder: false,
    id: 349247002,
    ino: 59109745109376900,
    dev: 2655223399
  }
}
[2023-04-05 11:06:01.205] [info]  Generating actions needed to sync
[2023-04-05 11:06:01.438] [debug] Current local before {
  Crypto: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 34339947158839948,
    dev: 2655223399
  },
  Cryptomator: {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 68679894317538770,
    dev: 2655223399
  },
  'Cryptomator/NFTs': {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 19421773393173988,
    dev: 2655223399
  },
  'Cryptomator/NFTs/XXXXX': {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 34339947158838844,
    dev: 2655223399
  },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
    modtime: 1680560357,
    size: 549363,
    isFolder: false,
    ino: 18858823439707532,
    dev: 2655223399
  },
  'desktop.ini': {
    modtime: 1680559416,
    size: 46,
    isFolder: false,
    ino: 434034414087847200,
    dev: 2655223399
  },
  Devices: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 41658296553316880,
    dev: 2655223399
  },
  'Devices/iPad': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 108367866033742720,
    dev: 2655223399
  },
  'Devices/iPhone': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 18577348463043524,
    dev: 2655223399
  },
  'Devices/Kindle': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 10977524091855992,
    dev: 2655223399
  },
  'Devices/Pixel': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 128915539333620900,
    dev: 2655223399
  },
  'Devices/SilverBox': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 115967690404930510,
    dev: 2655223399
  },
  Family: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 30117822508180270,
    dev: 2655223399
  },
  Personal: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 144678138029288960,
    dev: 2655223399
  },
  'Personal/Documents': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 21673573206859864,
    dev: 2655223399
  },
  'Personal/Documents/IDs': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 23925373020546350,
    dev: 2655223399
  },
  'Personal/Documents/Reciepts': {
    modtime: 1680666424,
    size: 0,
    isFolder: true,
    ino: 22236523160281310,
    dev: 2655223399
  },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
    modtime: 1680560599,
    size: 29412,
    isFolder: false,
    ino: 59109745109376900,
    dev: 2655223399
  },
  'Personal/Photography': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 68961369294251280,
    dev: 2655223399
  },
  zToSort: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 81909218222821150,
    dev: 2655223399
  },
  'zToSort - Copy': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 41939771530019510,
    dev: 2655223399
  }
}
[2023-04-05 11:06:01.440] [debug] Current remote before {
  'desktop.ini': { modtime: 1680559416, size: '46', isFolder: false, id: 349246287 },
  'zToSort - Copy': { modtime: 1680667468, size: 0, isFolder: true, id: 65969060 },
  zToSort: { modtime: 1680637028, size: 0, isFolder: true, id: 65964291 },
  Devices: { modtime: 1680559982, size: 0, isFolder: true, id: 65933382 },
  'Devices/iPad': { modtime: 1680560486, size: 0, isFolder: true, id: 65933415 },
  'Devices/iPhone': { modtime: 1680559998, size: 0, isFolder: true, id: 65933391 },
  'Devices/SilverBox': { modtime: 1680559998, size: 0, isFolder: true, id: 65933390 },
  'Devices/Kindle': { modtime: 1680559998, size: 0, isFolder: true, id: 65933389 },
  'Devices/Pixel': { modtime: 1680559998, size: 0, isFolder: true, id: 65933387 },
  Cryptomator: { modtime: 1680559885, size: 0, isFolder: true, id: 65933369 },
  'Cryptomator/NFTs': { modtime: 1680560385, size: 0, isFolder: true, id: 65933404 },
  'Cryptomator/NFTs/XXXXX': { modtime: 1680560396, size: 0, isFolder: true, id: 65933405 },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
    modtime: 1680560357,
    size: '549363',
    isFolder: false,
    id: 349246863
  },
  Crypto: { modtime: 1680559861, size: 0, isFolder: true, id: 65933366 },
  Personal: { modtime: 1680558336, size: 0, isFolder: true, id: 65933311 },
  'Personal/Documents': { modtime: 1680559830, size: 0, isFolder: true, id: 65933361 },
  'Personal/Documents/Reciepts': { modtime: 1680560604, size: 0, isFolder: true, id: 65933422 },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
    modtime: 1680560599,
    size: '29412',
    isFolder: false,
    id: 349247002
  },
  'Personal/Documents/IDs': { modtime: 1680560676, size: 0, isFolder: true, id: 65933421 },
  'Personal/Photography': { modtime: 1680559808, size: 0, isFolder: true, id: 65933359 },
  Family: { modtime: 1680558336, size: 0, isFolder: true, id: 65933310 }
}
[2023-04-05 11:06:01.441] [debug] Local deltas {
  Crypto: { delta: 'NEW' },
  Cryptomator: { delta: 'NEW' },
  'Cryptomator/NFTs': { delta: 'NEW' },
  'Cryptomator/NFTs/XXXXX': { delta: 'NEW' },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': { delta: 'UNCHANGED' },
  'desktop.ini': { delta: 'UNCHANGED' },
  Devices: { delta: 'NEW' },
  'Devices/iPad': { delta: 'NEW' },
  'Devices/iPhone': { delta: 'NEW' },
  'Devices/Kindle': { delta: 'NEW' },
  'Devices/Pixel': { delta: 'NEW' },
  'Devices/SilverBox': { delta: 'NEW' },
  Family: { delta: 'NEW' },
  Personal: { delta: 'NEW' },
  'Personal/Documents': { delta: 'NEW' },
  'Personal/Documents/IDs': { delta: 'NEW' },
  'Personal/Documents/Reciepts': { delta: 'NEW' },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': { delta: 'UNCHANGED' },
  'Personal/Photography': { delta: 'NEW' },
  zToSort: { delta: 'NEW' },
  'zToSort - Copy': { delta: 'NEW' }
}
[2023-04-05 11:06:01.442] [debug] Remote deltas {
  'desktop.ini': { delta: 'UNCHANGED' },
  'zToSort - Copy': { delta: 'NEW' },
  zToSort: { delta: 'NEW' },
  Devices: { delta: 'NEW' },
  'Devices/iPad': { delta: 'NEW' },
  'Devices/iPhone': { delta: 'NEW' },
  'Devices/SilverBox': { delta: 'NEW' },
  'Devices/Kindle': { delta: 'NEW' },
  'Devices/Pixel': { delta: 'NEW' },
  Cryptomator: { delta: 'NEW' },
  'Cryptomator/NFTs': { delta: 'NEW' },
  'Cryptomator/NFTs/XXXXX': { delta: 'NEW' },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': { delta: 'UNCHANGED' },
  Crypto: { delta: 'NEW' },
  Personal: { delta: 'NEW' },
  'Personal/Documents': { delta: 'NEW' },
  'Personal/Documents/Reciepts': { delta: 'NEW' },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': { delta: 'UNCHANGED' },
  'Personal/Documents/IDs': { delta: 'NEW' },
  'Personal/Photography': { delta: 'NEW' },
  Family: { delta: 'NEW' }
}
[2023-04-05 11:06:01.452] [debug] PULL FOLDERS:  [
  "Crypto",
  "Cryptomator",
  "Cryptomator/NFTs",
  "Cryptomator/NFTs/XXXXX",
  "Devices",
  "Devices/iPad",
  "Devices/iPhone",
  "Devices/Kindle",
  "Devices/Pixel",
  "Devices/SilverBox",
  "Family",
  "Personal",
  "Personal/Documents",
  "Personal/Documents/IDs",
  "Personal/Documents/Reciepts",
  "Personal/Photography",
  "zToSort"
] [
  "zToSort - Copy"
]
[2023-04-05 11:06:01.466] [error] Error: An error occured creating a folder of the level: 0
    at file:///C:/Users/[Window10-UserName]/AppData/Local/Programs/internxt-drive/resources/app.asar/dist/sync/renderer.js:8:440460
[2023-04-05 11:06:01.466] [debug] Queue rename in local []
[2023-04-05 11:06:01.467] [debug] Queue rename in remote []
[2023-04-05 11:06:01.467] [debug] Queue pull from local []
[2023-04-05 11:06:01.468] [debug] Queue pull from remote []
[2023-04-05 11:06:01.468] [debug] Queue delete from local []
[2023-04-05 11:06:01.469] [debug] Queue delete from remote []
[2023-04-05 11:06:01.470] [info]  Folders deleted in local []
[2023-04-05 11:06:01.470] [info]  Folders deleted in remote []
[2023-04-05 11:06:01.471] [info]  Finalizing sync
[2023-04-05 11:06:01.678] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Crypto, parentFolderId: 65933309"
  }
}
[2023-04-05 11:06:01.896] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Cryptomator, parentFolderId: 65933309"
  }
}
[2023-04-05 11:06:02.046] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Devices, parentFolderId: 65933309"
  }
}
[2023-04-05 11:06:02.050] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Personal, parentFolderId: 65933309"
  }
}
[2023-04-05 11:06:02.052] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Cryptomator/NFTs, parentFolderId: 65933369"
  }
}
[2023-04-05 11:06:02.122] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Devices/iPad, parentFolderId: 65933382"
  }
}
[2023-04-05 11:06:02.268] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Devices/iPhone, parentFolderId: 65933382"
  }
}
[2023-04-05 11:06:02.272] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Devices/Pixel, parentFolderId: 65933382"
  }
}
[2023-04-05 11:06:02.273] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Devices/Kindle, parentFolderId: 65933382"
  }
}
[2023-04-05 11:06:02.500] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Personal/Documents, parentFolderId: 65933311"
  }
}
[2023-04-05 11:06:02.502] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Cryptomator/NFTs/XXXXX, parentFolderId: 65933404"
  }
}
[2023-04-05 11:06:02.503] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Personal/Photography, parentFolderId: 65933311"
  }
}
[2023-04-05 11:06:02.723] [debug] Current local: {
  Crypto: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 34339947158839948,
    dev: 2655223399
  },
  Cryptomator: {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 68679894317538770,
    dev: 2655223399
  },
  'Cryptomator/NFTs': {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 19421773393173988,
    dev: 2655223399
  },
  'Cryptomator/NFTs/XXXXX': {
    modtime: 1680666422,
    size: 0,
    isFolder: true,
    ino: 34339947158838844,
    dev: 2655223399
  },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
    modtime: 1680560357,
    size: 549363,
    isFolder: false,
    ino: 18858823439707532,
    dev: 2655223399
  },
  'desktop.ini': {
    modtime: 1680559416,
    size: 46,
    isFolder: false,
    ino: 434034414087847200,
    dev: 2655223399
  },
  Devices: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 41658296553316880,
    dev: 2655223399
  },
  'Devices/iPad': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 108367866033742720,
    dev: 2655223399
  },
  'Devices/iPhone': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 18577348463043524,
    dev: 2655223399
  },
  'Devices/Kindle': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 10977524091855992,
    dev: 2655223399
  },
  'Devices/Pixel': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 128915539333620900,
    dev: 2655223399
  },
  'Devices/SilverBox': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 115967690404930510,
    dev: 2655223399
  },
  Family: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 30117822508180270,
    dev: 2655223399
  },
  Personal: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 144678138029288960,
    dev: 2655223399
  },
  'Personal/Documents': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 21673573206859864,
    dev: 2655223399
  },
  'Personal/Documents/IDs': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 23925373020546350,
    dev: 2655223399
  },
  'Personal/Documents/Reciepts': {
    modtime: 1680666424,
    size: 0,
    isFolder: true,
    ino: 22236523160281310,
    dev: 2655223399
  },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
    modtime: 1680560599,
    size: 29412,
    isFolder: false,
    ino: 59109745109376900,
    dev: 2655223399
  },
  'Personal/Photography': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 68961369294251280,
    dev: 2655223399
  },
  zToSort: {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 81909218222821150,
    dev: 2655223399
  },
  'zToSort - Copy': {
    modtime: 1680666535,
    size: 0,
    isFolder: true,
    ino: 41939771530019510,
    dev: 2655223399
  }
}
[2023-04-05 11:06:02.724] [debug] Current remote: {
  'desktop.ini': { modtime: 1680559416, size: '46', isFolder: false, id: 349246287 },
  'zToSort - Copy': { modtime: 1680667468, size: 0, isFolder: true, id: 65969060 },
  zToSort: { modtime: 1680637028, size: 0, isFolder: true, id: 65964291 },
  Devices: { modtime: 1680559982, size: 0, isFolder: true, id: 65933382 },
  'Devices/iPad': { modtime: 1680560486, size: 0, isFolder: true, id: 65933415 },
  'Devices/iPhone': { modtime: 1680559998, size: 0, isFolder: true, id: 65933391 },
  'Devices/SilverBox': { modtime: 1680559998, size: 0, isFolder: true, id: 65933390 },
  'Devices/Kindle': { modtime: 1680559998, size: 0, isFolder: true, id: 65933389 },
  'Devices/Pixel': { modtime: 1680559998, size: 0, isFolder: true, id: 65933387 },
  Cryptomator: { modtime: 1680559885, size: 0, isFolder: true, id: 65933369 },
  'Cryptomator/NFTs': { modtime: 1680560385, size: 0, isFolder: true, id: 65933404 },
  'Cryptomator/NFTs/XXXXX': { modtime: 1680560396, size: 0, isFolder: true, id: 65933405 },
  'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
    modtime: 1680560357,
    size: '549363',
    isFolder: false,
    id: 349246863
  },
  Crypto: { modtime: 1680559861, size: 0, isFolder: true, id: 65933366 },
  Personal: { modtime: 1680558336, size: 0, isFolder: true, id: 65933311 },
  'Personal/Documents': { modtime: 1680559830, size: 0, isFolder: true, id: 65933361 },
  'Personal/Documents/Reciepts': { modtime: 1680560604, size: 0, isFolder: true, id: 65933422 },
  'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
    modtime: 1680560599,
    size: '29412',
    isFolder: false,
    id: 349247002
  },
  'Personal/Documents/IDs': { modtime: 1680560676, size: 0, isFolder: true, id: 65933421 },
  'Personal/Photography': { modtime: 1680559808, size: 0, isFolder: true, id: 65933359 },
  Family: { modtime: 1680558336, size: 0, isFolder: true, id: 65933310 }
}
[2023-04-05 11:06:02.732] [info]  Sync done, result:  {
  status: 'NOT_IN_SYNC',
  diff: {
    filesNotInLocal: [],
    filesNotInRemote: [],
    filesWithDifferentModtime: [
      'Crypto',
      'Cryptomator',
      'Cryptomator/NFTs',
      'Cryptomator/NFTs/XXXXX',
      'Devices',
      'Devices/iPad',
      'Devices/iPhone',
      'Devices/Kindle',
      'Devices/Pixel',
      'Devices/SilverBox',
      'Family',
      'Personal',
      'Personal/Documents',
      'Personal/Documents/IDs',
      'Personal/Documents/Reciepts',
      'Personal/Photography',
      'zToSort',
      'zToSort - Copy'
    ],
    filesInSync: {
      'Cryptomator/NFTs/XXXXX/XXXXX.jpeg': {
        modtime: 1680560357,
        size: '549363',
        isFolder: false,
        id: 349246863,
        ino: 18858823439707532,
        dev: 2655223399
      },
      'desktop.ini': {
        modtime: 1680559416,
        size: '46',
        isFolder: false,
        id: 349246287,
        ino: 434034414087847200,
        dev: 2655223399
      },
      'Personal/Documents/Reciepts/04042023-Invoice-INXT-4335.pdf': {
        modtime: 1680560599,
        size: '29412',
        isFolder: false,
        id: 349247002,
        ino: 59109745109376900,
        dev: 2655223399
      }
    }
  }
}
[2023-04-05 11:06:02.734] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Personal/Documents/IDs, parentFolderId: 65933361"
  }
}
[2023-04-05 11:06:02.734] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Personal/Documents/Reciepts, parentFolderId: 65933361"
  }
}
[2023-04-05 11:06:02.927] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: Family, parentFolderId: 65933309"
  }
}
[2023-04-05 11:06:02.928] [error] {
  "name": "BAD_RESPONSE",
  "details": {
    "action": "Creating folder in drive server",
    "additionalInfo": "res: {\n  \"status\": 500,\n  \"body\": \"\"\n}, folderName: zToSort, parentFolderId: 65933309"
  }
}

**Comment by fvsegarra** [comment]
Hi there,
Please log out, update to our v2.1.2 release https://github.com/internxt/drive-desktop/releases/tag/v2.1.2 log back in and let us know if the issue persists. If it does, please send all details alongside your log files to hello@internxt.com
Thank you!
