### ISSUE TITLE
[Security improvement] Logged in after desinstalation

### ISSUE THREAD

**Issue by Barraguesh** [internxt/drive-desktop#24]
I uninstalled the version I had because it was throwing Java runtime exceptions (update failed, was many versions behind so I see it as expected behavior) but after install, I realized the account was still logged in.

I think this is a security problem and the session should be cleared on uninstall.

**Comment by sg-gs** [comment]
@zhihaoSAR

**Comment by JoanMora** [comment]
For Linux and macOS, the current workflow of our app is the standard. For windows, the standard is not to be logged in when reinstalling. This issue is fixed in version 1.2.13.
