### ISSUE TITLE
Can not choose between "full sync" or "upload only". Bug.

### ISSUE THREAD

**Issue by jlghub** [internxt/drive-desktop#38]
Version 1.4.0 (windows)

There is no option to select "full sync" or "upload only".

**Comment by jhendrik1** [comment]
Version 1.4.2 (windows)

Although explicitly advertised during the setup program, the option "Upload only" is still missing.

**Comment by JoanMora** [comment]
The next version of the Desktop app will include selective sync which is a general case of full and upload only.

**Comment by Juasmis** [comment]
I am using Internxt 1.9.7 and I see no option in preferences about Selective Sync, was this implemented?
