### ISSUE TITLE
Proposal: accessing files from a Virtual Drive Desktop (specific files and folders to be available offline)

### ISSUE THREAD

**Issue by jlghub** [internxt/drive-desktop#39]
accessing files from a Virtual Drive Desktop on computer and choosing specific files and folders to be available offline

**Comment by caouic** [comment]
It would be great. I don't have 1TB on my local Drive. Choose folder sync state on web app or on Windows app (case of multiple devices with the same Internxt account)

**Comment by jlghub** [comment]
We really need this feature. Have you got it in your roadmap?
