### ISSUE TITLE
Enhancement Proposal for improved UX on letting users know that files are safe

### ISSUE THREAD

**Issue by zrml** [internxt/drive-desktop#44]
It's very difficult to verify what has been backed up.
IOW comparing my directory & file structures vs what I see on the web-ui is time consuming and not my duty as a user.
A more intuitive mechanism is needed to avoid userfrustration.

A green marker should be added to the files to let the user know that files are safely backed up.
This is a common strategy to let the user know that things are OK or not OK ( in case of large files that may take longer to be saved off).

Thanks

**Comment by AlexMenor** [comment]
Hey @zrml, thanks for your feedback.

I feel that you are right, we'll consider it for the next release.

**Comment by aboredvaro** [comment]
Hi @zrml!
Thanks for sharing your comment, we're always happy to hear what our users think and feel when using Internxt products 🤗!

We are aware of this issue and understand your frustration. This feature is on our roadmap and is being considered for upcoming releases, we will let you know when it will be publicly available via our newsletter or twitter.

We encourage you to send us this kind of feedback through our ([email](help@internxt.com)) or join our ([telegram](https://t.me/Internxt)), where our 8k+ member community actively shares feedback every day to improve the Internxt experience.

Again thanks for your feedback, it's very valuable for us 😄!

Álvaro Hernández,
Lead Product Designer at Internxt
