### ISSUE TITLE
No support for 0 byte files

### ISSUE THREAD

**Issue by meticoeus** [internxt/drive-desktop#45]
From renderer.log
[error] Error uploading file: ... Error: Error: Warning:File %s, Filesize 0

Plenty of scenarios result in having 0 byte files such as unpacked applications or new files that haven't been edited yet.

Is it possible for the internxt to support these somehow?

**Comment by AlexMenor** [comment]
Hey @meticoeus, thanks for opening an issue:

Supporting these files isn't trivial for us because our processes to encrypt, fragment and so on.

We feel like these kind of files are mostly garbage/temp files and we ignore them but we could be wrong.

What workflows that you have are being disrupted by this issue, so we can consider supporting them?

Thanks

**Comment by meticoeus** [comment]
1 example is apps with included source code which occasionally have empty files that haven't had any code added yet but can still potentially be referenced somewhere. A specific example is renpy games which tend to have stubbed init.py files that may or may not have any code in them in the current game version. I've been fixing these by just adding a single new line character so the files upload. Trash files like empty logs I've just been deleting.

The annoying problem with this limitation is that the client doesn't respond to clicking on these failed uploads to take you to them so that you can change them or delete them. Instead you currently need to hunt in the log for upload errors to get the file path.

A short term solution would be fixing the desktop client so that clicking these error items would open their file location just like clicking successfully uploaded files. This is probably a  "good enough" solution until a stronger use case for supporting empty files is made.

For reference I'm using the app on Pop OS 21.04 but downloading the AppImage file from the releases page on github. Clicking uploaded files in the activity log opens the folder containing the file in Nautilus, the pre-installed GUI file explorer. Clicking files that failed with any kind of error does nothing.

If this is going to remain a long term limitation it may also be useful to add a more specific error message for these in the GUI to educate less technical users that aren't going to dig through the log.

A short term solution would be fixing the desktop client so that clicking these error items would open their file location just like clicking successfully uploaded files. This is probably a  "good enough" solution until a stronger use case for supporting empty files is made.

**Comment by AlexMenor** [comment]
Thanks for your elaboration @meticoeus, I'll bring it up to the team.

**Comment by Slashhh-es** [comment]
I also need this feature to organize better my self, and organize the space.
Also, would be nice to synchronize the empty folders to skip a file .internxt-empty in that folder (now days you can create an empty folder from the web).

**Comment by AlexMenor** [comment]
That's a nice suggestion @Slashhh-es.

Thanks :)

**Comment by JoanMora** [comment]
Hello, @Slashhh-es @meticoeus this is something we will try to implement in new versions of the desktop sync process. As mentioned git does it using .gitkeep files and something similar can be done. This won't solve our current limitation of not uploading empty files in any case which is a different challenge. Thanks for the feedback!.

**Comment by ecobux** [comment]
I'm looking forward and I will wait for this feature before using Internxt in my work. For my coworkers, "syncing" simply means that the file and folder structure will look _exactly_ the same on all devices. Most users won't understand the difficulties of the technical implementation. Rather than accepting confusing discrepancies or applying a workaround, they would probably just move on to another cloud service.
