### ISSUE TITLE
Unable to make a Folder locally available

### ISSUE THREAD

**Issue by mohammadmoein** [internxt/drive-desktop#507]
I am currently facing issues  with make a folder that contains numerous files locally available.  Actually, I can not use the windows app at all and have no access to my files. This screenshot pops up and downloads nothing

![image](https://github.com/user-attachments/assets/845e0c5a-770b-436a-a0e3-93df93c6512d)

**Comment by fvsegarra** [comment]
Hi there,
Please log out, update to our v2.1.2 release https://github.com/internxt/drive-desktop/releases/tag/v2.1.2 log back in and let us know if the issue persists. If it does, please send all details alongside your log files to hello@internxt.com
Thank you!
