### ISSUE TITLE
After standby or network change, the syncing status is in an endless loop

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#508]
Not sure which triggers this, but when I come back from standby after changing the network (either condition might be enough to trigger), Internxt Desktop (Windows, version 2.1.0) is always showing that it synchronizes and never ends.

Already reported via email, but using this for tracking and possibly direct interaction with the devs.

**Comment by claell** [comment]
This might have been fixed in between. Leaving open a bit longer to confirm.

**Comment by fvsegarra** [comment]
Hi there,
Please log out, update to our v2.1.2 release https://github.com/internxt/drive-desktop/releases/tag/v2.1.2 log back in and let us know if the issue persists. If it does, please send all details alongside your log files to hello@internxt.com
Thank you!

**Comment by claell** [comment]
I did that. It didn't occur again, in the meantime. Let's see whether it will stay that way. ;)
