### ISSUE TITLE
Seldomly, the drive tray icon is not reacting to mouse clicks

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#509]
Happened some times for me now. Usually works again after waiting a bit. Seems to be some internal hang up.

**Comment by fvsegarra** [comment]
Hi there,
Please log out, update to our v2.1.2 release https://github.com/internxt/drive-desktop/releases/tag/v2.1.2 log back in and let us know if the issue persists. If it does, please send all details alongside your log files to hello@internxt.com
Thank you!

**Comment by claell** [comment]
Persists. Will follow up via email, then.
