### ISSUE TITLE
Moving folders in Windows Explorer is very slow and fails

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#513]
I dragged a folder to another in Windows Explorer. It contains some subfolders and a bunch of files. The folder is Cloud only, so not downloaded to Windows.

This operation is pretty slow, see the progress (took about 20 seconds to get there for 30 elements):

![grafik](https://github.com/user-attachments/assets/f6e85803-7c34-4126-bb17-3b0edb983cac)

Then, it fails:

![grafik](https://github.com/user-attachments/assets/0c45474a-f9bd-4efb-ae9e-2e42b3902274)

When I click on "repeat", it doesn't work.

Clicking "skip" results in the next elements not being found:

![grafik](https://github.com/user-attachments/assets/d5605f2f-f7fc-4afb-b58c-bf4859a64ca8)

**Comment by claell** [comment]
I am rather confident that this not only lead to an incomplete move (items got partly moved), but also to trashing items (one subfolder wasn't moved, but put to trash).

**Comment by fvsegarra** [comment]
Hi there,
Can you please share more details on this with our support team at hello@internxt.com including the log files of the app so that we can investigate this issue properly? Thank you

**Comment by claell** [comment]
Alright. Seems you are relying on Jira (and Intercom), internally, which makes tracking issues on GitHub probably not that convenient?
