### ISSUE TITLE
Original modification date is not kept

### ISSUE THREAD

**Issue by claell** [internxt/drive-desktop#514]
Uploading items doesn't keep their original modification date. Not sure about downloading (syncing from web to desktop).

Additionally, not sure about the creation date, either.

**Comment by claell** [comment]
This also happens for moving files in Windows Explorer. This also changes the upload date.

![grafik](https://github.com/user-attachments/assets/e3b0a150-3952-4899-8a0c-2a7e9672e037)

**Comment by fvsegarra** [comment]
Thanks for reporting, looking into it right now
