### ISSUE TITLE
CPU usage with drive desktop app running (windows)

### ISSUE THREAD

**Issue by maxmaxxxxx** [internxt/drive-desktop#516]
keep the desktop drive app (windows) in the background, it overloads the CPU and the PC remains severely slowed down.
The desktop app soaks up about 80% of the CPU resources.

**Comment by CanadianBeaver** [comment]
I have same issue

<img width="1270" height="439" alt="Image" src="https://github.com/user-attachments/assets/0aa398a5-675b-4476-8251-ade684e3c9cc" />

I don't mean to jump to conclusions, but is there any chance Internxt might be doing something like hidden mining? The CPU usage seems oddly high when it's not actively syncing.
