### ISSUE TITLE
Backups are not created / shown error

### ISSUE THREAD

**Issue by MrMasterbay** [internxt/drive-desktop#521]
Backup shows sucessful but didn´t upload anything.

![backups-don-t-work-v0-mlobvnh0w3ud1](https://github.com/user-attachments/assets/fffdcf01-c3f0-4f63-90a8-e2f9d883fa95)

![grafik](https://github.com/user-attachments/assets/aed2fbfd-a22d-4d4e-b84d-820f81709585)

Log shows only this:
![grafik](https://github.com/user-attachments/assets/2d0ff390-398d-4388-82f3-1a5805e9c8d7)

Reinstalling the software didn´t help. Signing out / and in also didn´t work.

**Comment by fvsegarra** [comment]
Hi there, could you send us this message alongside the app log files to hello@internxt.com please? That way we can investigate this issue in more depth. Thanks!
