### ISSUE TITLE
How to do this steps :

### ISSUE THREAD

**Issue by shaka92** [internxt/drive-desktop#53]
Hello, can u explain how to do the first two steps?
Create a .npmrc file from the .npmrc.template example provided in the repo.
Replace TOKEN with your own Github Personal Access Token with read:packages permission ONLY

**Comment by AlexMenor** [comment]
Hello @shaka92, that token has to be created from someone that is part of the Internxt organization.

**Comment by shaka92** [comment]
So can I not build this app by own ?

**Comment by AlexMenor** [comment]
We are figuring out a few things that would allow us to make public a repo that is currently private.
You'll be able to build it on your own soon.
