### ISSUE TITLE
Switch desktop applications to mapped network drive client (FUSED).

### ISSUE THREAD

**Issue by b3pio** [internxt/drive-desktop#56]
Current desktop application (for windows at least - yet to test linux/macOS, but I assume it functions the same) it seems a bit redundant having to store files both in the cloud and on the hard drive as a 'sync folder'. Defeats the purpose for using the internxt cloud storage to clear desktop hard drive space.

Solution would be to mimic pCloud, Icedrive etc by using a mapped network drive client instead. (fuse?) So for example in a windows system it could be mounted as I: drive perhaps.

Without the webdav option we cant even use other solutions, which I'd prefer not to use such paid proprietary software to fill this gap like Mountain Duck and ExpanDrive.

**Comment by Desibabe** [comment]
I had 29 files on both local mapped network drive as well as on a cloud. However, after upgrading from 1.4.2. to 1.5.0, local mapped drive has 54 files and 29 files in the cloud. Files have been changed in local drive from xxxx to xxxx.local and xxxx.remote. Cloud has xxxx.remote. I didn't like this approach in 1.5.0 because local drive no has doubled, I reverted back to 1.4.2 from 1.5.0. There should be an eay solution. Thanks.

**Comment by b3pio** [comment]
@Desibabe Ok so to my knowledge v1.4.2 was a 'sync folders' setup, so in order to work you must store files both in the cloud and on your hard drive. So if you want to use cloud storage to clear hard drive space this approach doesn’t work, obviously.

Then I think v1.5.0 looks like its switched to 'selective sync' so you can turn sync off for specific folders and, in doing so, those folders will only be stored in the cloud and not on your hard drive.
The downside to this is that you’ll no longer be able to view folder contents in your file system for folders that you’ve turned sync off for. In order to see what files are there, you’ll either need to turn sync back on for the folder or login into the web interface for your cloud storage solution.

What I would love to see (so I would actually utilize my internxt storage more) is the desktop client changed to a 'network drive client' (or sometimes known as a Virtual Drive). A network drive is a mapped drive. It looks like a normal drive letter in your local file system, but instead of space on your computer hard drive, the drive letter points to a server hard drive. For example pcloud/icedrive do this very well.

**Comment by meticoeus** [comment]
While this would be a useful option, having the option to keep a copy of files offline is also important for some users. Adding the ability to select which folders you want to keep a local copy of vs those you only want in the cloud would be a better solution that a network only system where you lose all access to your files when your connection dies.

**Comment by b3pio** [comment]
@meticoeus You can easily keep selected cloud stored files for offline use in a FUSE virtual drive setup with no network connection, (eg before you are without network, right click > save for offline for example) With a fused virtual drive you can choose what is stored for cloud only and what is stored in the cloud and also saved for offline use. Its the best option here and would solve alot of the problems internxt is currently having. Look at IceDrive, pCloud, Google Drive, OneDrive, Dropbox, iCloud etc they all use a form of virtual fused drive as their desktop clients.

**Comment by meticoeus** [comment]
@b3pio thanks for the information, I've looked further into what FUSE is and is capable of. My understanding so far is that you can support offline files if you implement it but the devs still need to implement online only or support for a mix of a local synced cache + online-only files.

I agree this would be beneficial.

**Comment by b3pio** [comment]
No movement/updates on this potential enhancement 7 months on?
