### ISSUE TITLE
Win 11 Bug - Application Window Keep Expand Horizontally

### ISSUE THREAD

**Issue by lrmalaysia** [internxt/drive-desktop#63]
When open the preference window it keep expand horizontally even over screen. Below is the video for your reference.

https://siasky.net/vACfmAVZY5sUx_I86RL4b_Lg0HAiKoiIF0sr5tbGwV1x4w

**Comment by AlexMenor** [comment]
Hi @lrmalaysia, do you have any special display layout/setup? The window width is fixed.

**Comment by lrmalaysia** [comment]
> Hi @lrmalaysia, do you have any special display layout/setup? The window's width is fixed.

Hi, I'm using Microsoft Surface Pro 7. Just the internal default screen display. I set nothing. You can see as video showed. I just download the version 1.5.1 yesterday. Once open preference then it keep expand horizontally.
