### ISSUE TITLE
libgconf dependency still required?

### ISSUE THREAD

**Issue by wolfenrain** [internxt/drive-desktop#7]
I tried to install the deb file on my Arch-based system and couldn't because of the `libgconf` dependency.

Reading a bit on the AUR I noticed [this comment](https://aur.archlinux.org/packages/gconf/#pinned-723510) stating that in most cases electron apps don't necessary need to depend on it, but that it is just a leftover from a legacy. 

And I wondered if it is still required, because right now I wont be able to install the desktop on my system. And that would be quite a shame.

**Comment by fvsegarra** [comment]
Hi there,
We just updated the Desktop app (v1.1.7). Please check if you're still experiencing this issue
