### ISSUE TITLE
v1.1.6 No longer triggers login page

### ISSUE THREAD

**Issue by Hyuchia** [internxt/drive-desktop#8]
When doing a fresh install, all versions up to v1.1.5 allow you to log in but v1.1.6 no longer shows the login window.

My guess is it has to do with the addition of the `maybeShowWindow` function, it may be emitting the event before its handler gets registered: https://github.com/internxt/drive-desktop/blob/d0df51b104c83a391ddd8d52ca90bac7cc52747a/src/main/index.js#L243-L255

I'm not sure but I also think given the check here: https://github.com/internxt/drive-desktop/blob/d0df51b104c83a391ddd8d52ca90bac7cc52747a/src/main/index.js#L220-L224

The `mainWindow` variable should be initialized to `null` instead of leaving it as `undefined`. 

Unfortunately, I haven't been able to build the app due to npm running into some issues building the `storj` module so I haven't been able to try to fix it myself. Any advice on how to build and run the app?

Running on:
elementary OS 5.1.6 (based in Ubuntu 18.05.4)

**Comment by fvsegarra** [comment]
Hi there,
We tried on Windows, macOS, and Linux, and the login window prompted, as long as you didn't have a saved session on your .internxt-desktop folder. Remove that temp folder from your computer and try opening the app; the login box should prompt
<img width="927" alt="Screen Shot 2020-07-07 at 12 38 09" src="https://user-images.githubusercontent.com/13625808/86769047-cac34b80-c04e-11ea-8907-4e61f839157e.png">

**Comment by Hyuchia** [comment]
Even when deleting the `.internxt-drive` and any other related directory the login still wouldn't show up. This seems to have been fixed by `v1.1.7` though so this can be closed now.
