### ISSUE TITLE
Website drive.deb not working

### ISSUE THREAD

**Issue by mkauzlar** [internxt/drive-desktop#82]
when joining the there is a link to install the app. This downloads the drive.deb
After installation it fails to start with:

`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[38087:0222/072720.920359:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)`

the drive.deb installs the version 1.5.2 and the OS is Ubuntu 22.04

I downloaded then the version 1.6 from github and that one works.
I advise you to upgrade the app offered on your website

**Comment by sg-gs** [comment]
We currently support Ubuntu 22.04 and have updated that version on the link to install the app a long time ago. Please, contact support at hello@internxt.com if this issue persists
