### ISSUE TITLE
[Feature request] Select different folders on sync mode

### ISSUE THREAD

**Issue by PolGZ** [internxt/drive-desktop#85]
Select **different folders** on local device to sync, and create/select **target folders** on the "cloud".

Example:

- Work PC folder: C:\User\Documents\Work to internxt folder that I could also name Work; it syncs there and then, I also sync it locally on my laptop /home/user/Documents/Work, because I work from home.
- Laptop local folder /home/user/Photos/ to internxt folder that I name Photos. I wan't to sync that in my tablet but I don't want to sync that with my work PC. And I also would want to check those photos from the smartphone app, without locally syncthing them in this case, because it takes so much space (so access them with internet connection) or to view them from a browser where I log in.

Right now, one can only pick a single folder and all it's data is thrown at internxt directly. You can't put it on a single named folder and select on which devices you want it also synchronized locally.

Right now, you "need" to have the same content on all your devices instead of organizing it how you like it on each one.

label:enhancement

**Comment by noticons** [comment]
(if I'm understanding you correctly) Agreed, being able to choose specific folders to sync--and not just as a backup--would be great.

**Comment by JoanMora** [comment]
Hello, we currently work syncing just one folder but our sync is ready to sync folders separately (behaviour described by @PolGZ). This feature request is in our roadmap, at the moment we have been focusing on improving performance and stability overall. Thanks for your feedback.
