### ISSUE TITLE
Looks like other of your devices is already syncing, we'll try again later

### ISSUE THREAD

**Issue by derEremit** [internxt/drive-desktop#87]
message: 

Looks like other of your devices is already syncing, we'll try again later

I think that happened since upgrading to 1.5.0

I only have one device currently running but cant get this to work again for days

currently on deb package 1.7.0 on kde neon  / ubuntu lts 20.04

**Comment by derEremit** [comment]
still with 1.7.1

maybe more is broken:
![image](https://user-images.githubusercontent.com/818388/156585329-d0c61b62-3b9e-4376-a668-b19422dce0a1.png)

**Comment by devhawkio** [comment]
1.8.0 as well. The app is unusable.

**Comment by killer23d** [comment]
Confirmed same problem on 1.8.0 as well.

**Comment by noticons** [comment]
> currently on deb package 1.7.0 on kde neon / ubuntu lts 20.04

**Comment by acuvic** [comment]
Same problem here with v1.8 - was working a week ago but cannot sync now
Running on Devuan/Debian distro

**Comment by RichardJECooke** [comment]
This app doesn't sync properly once the initial sync download is done. Tried on Windows and Ubuntu. Get this error message permanently. Going back to Dropbox :(

**Comment by sg-gs** [comment]
Hello guys, we are starting to put more effort into paying close attention to our beloved Desktop users community. The development team is very sorry to hear these things and in the past, we did not have enough resources to handle everything. 

Please if any of your problems persist, contact us via hello@internxt.com and we will handle your issues ASAP.
