### ISSUE TITLE
Non-existent support

### ISSUE THREAD

**Issue by metamorfasis** [internxt/drive-desktop#92]
I can't get my files downloaded. Can't get the app to sync. Updated today to 1.8.0 and nothing changed. This is the worst service ever because they reply weeks after a ticket is opened and then they have someone with very little English skills replying. In addition, there is Never a solution to anything.

**Comment by Barraguesh** [comment]
Contact support. You might have an account issue, I had it and the problem was the same, bad luck of being early adopters I guess. Back everything up to a local copy first. Good luck!
