### ISSUE TITLE
Login fails to: "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by TG0** [internxt/drive-desktop#93]
This error came, when I try to log in with the windows app, in win 10:

![internxt_login_failure](https://user-images.githubusercontent.com/29196123/159707888-e624214f-72be-4e31-86e9-1d92a7a4fff3.jpg)

Just downloaded the APP in my PC. The email was correct and the PWD contains characters:

- lower case letters
- capital letters
- numbers
- number sign character

The web site accepted the pwd just fine.

**Comment by AlexMenor** [comment]
it was probably a temporal error of our servers, can you try again?

**Comment by TG0** [comment]
Still the same. This is my work PC... but since I work from home, there should not be a FW blocking anything. Closed VPN too.
From the error msg I did not understand this could be a "server not available" type of thing.
I have Linux and Mac PCs too, my personal PCs, I can try with them a bit later, sat-sun probably.

**Comment by Desibabe** [comment]
I believe few school kids may have written this cloud program, I am wondering why haven't nobody notices/complained about this piece^%$#$ software.

**Comment by TG0** [comment]
Worked just fine in my Mac and in iPad. Closing this issue.
