### ISSUE TITLE
Widget button not showing in Gnome 41

### ISSUE THREAD

**Issue by paolo-sofia** [internxt/drive-desktop#95]
The widget button on the tray does not show up and whenever I use another window, the internxt window closes but the program is still running in background. I get this error in my machine with arch linux and gnome 41, while on another machine with pop-os and gnome 3.39 the widget button works perfectly without any problem. I'm using the latest Appimage version but I get the same error also with version 1.7 and 1.7.1, I attached below a couple of screenshots of what I get. 

![Schermata da 2022-03-27 12-19-52](https://user-images.githubusercontent.com/102464277/160277054-114c69af-025d-486c-8f4f-de89a086a59e.png)

![Schermata del 2022-03-27 12-28-10](https://user-images.githubusercontent.com/102464277/160277238-ad6df34a-b639-4137-8ba6-8014a06d978b.png)

**Comment by AlexMenor** [comment]
hi @paolo-sofia, have you tried kde?

**Comment by paolo-sofia** [comment]
hi @AlexMenor, I didn't tried with kde but I found a solution for gnome, I installed an extension called AppIndicator.

**Comment by AlexMenor** [comment]
im glad it worked @paolo-sofia
