### ISSUE TITLE
Application's window disappears every time it loses focus

### ISSUE THREAD

**Issue by x80486** [internxt/drive-desktop#97]
I've installed the latest (to this date) `AppImage`. I've notice that once the application's window loses focus, it disappears completely. I can only find the process within the operating system, and end/kill it.

The workaround is to execute the `AppImage` again and again to get access to the application, but the problem is that this action(s) start another completely new instance.

I'm using `Arch Linux` with `GNOME`.

**Comment by AlexMenor** [comment]
Perhaps you find this issue helpful https://github.com/internxt/drive-desktop/issues/95

**Comment by x80486** [comment]
Understood, but I think the application could be self-contained, and not rely on an (external) extension. My experience is that those break from time to time.

I think it's better if the application could be framed on its own window, with all the usual controls.

**Comment by AlexMenor** [comment]
Right now is intended to be used as a widget rather. Also, I understand that the extension is standard to get indicator from any app right?
