### ISSUE TITLE
Backups hang after less than 24 hours

### ISSUE THREAD

**Issue by lerlands** [internxt/drive-desktop#98]
I am running Internxt Drive v1.8.0 , running on linux mint 20.3 .

I have tried to run a backup of a few directories (high Gbytes of files) to my 1 Tb account. The network usage goes up, large logfiles are generated under ${USER}/.config/internxt-drive/logs. After less than 24 hours, the process seems to freeze (at around 50-75% completion), with no new traffic is observed. If I stop and restart the process, it starts at the very beginning again, and hangs in the same way.

Observing the behaviour, it looks like there are no optimisations. Backing up a Gbyte of files appears to happen as a full backup every time.

Backing up file systems has been successfully solved a number of times in the last few decades. The best example is 'rsync', which does selective copying, comparing both timestamps and checksums before going into the expensive task of overwriting the file(s). It has a number of switches and configuration settings to tailor the backup, can be interrupted, stopped and restarted with no loss of functionality, and contains a number of smart design choices learnt over the years.

I note that most of the internxt software is written in javascript or typescript. If the backup software has not been optimised with functionality similar to what 'rsync' provides, it might be an idea to study and learn from best practices in the 'rsync' source code. Further optimisations can be made making use of all the attributes stored alongside the files, to save re-computing checksums.

Any logfiles or further information, please do not hesitate to get back to me.

Thanks,
Lars.

![Internxt Drive_636](https://user-images.githubusercontent.com/4600677/165308943-a4086479-7976-42d7-8437-1099ad02f11a.png)

**Comment by AlexMenor** [comment]
Hi Lars, backups are not atomic, the process starts from 0% if restarted, but it doesnt mean that already uploaded files are copied again.

I don't know what could be stopping the process, feel free to send us logs through our ticket system.

**Comment by lerlands** [comment]
Here are the logs :-)
[renderer.log](https://github.com/internxt/drive-desktop/files/8564633/renderer.log)
